source "https://rubygems.org"

# Plain Jekyll 4 — built + deployed to GitHub Pages via Actions
# (see .github/workflows/pages.yml). No plugins required: the sitemap and
# robots.txt are generated by dependency-free Liquid templates in the repo.
gem "jekyll", "~> 4.3"

# Required by `jekyll serve` on Ruby 3+ (no longer part of the stdlib).
gem "webrick", "~> 1.8"
